version: '3'

services:
  auth-api:
    container_name: auth-api
    build:
      context: .
      dockerfile: ./apps/auth-api/Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.docker
    networks:
      - url_shortener_api_network

  url-shortener-api:
    container_name: url-shortener-api
    build:
      context: .
      dockerfile: ./apps/url-shortener-api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    env_file:
      - .env.docker
    networks:
      - url_shortener_api_network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: url_shortener_api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5432:5432'
    networks:
      - url_shortener_api_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  url_shortener_api_network:
    external: true
