name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: url_shortener_api_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v3

      - name: 🟢 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🟢 Ativar Corepack e instalar pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: 📦 Instalar dependências
        run: |
          pnpm install --frozen-lockfile
          pnpm add -D dotenv-cli -w

      - name: 🧪 Esperar banco de dados
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Esperando o banco subir..."
            sleep 2
          done

      - name: 🧹 Rodar Lint
        run: pnpm lint

      - name: 🧪 Rodar Testes
        run: |
          pnpm exec dotenv -e ./apps/auth-api/.env.test.local
          pnpm exec dotenv -e ./apps/url-shortener-api/.env.test.local
          pnpm exec dotenv -e ./packages/shared/.env.test.local
          pnpm test
