name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: url_shortener_api_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v3

      - name: 🟢 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependências
        run: |
          corepack enable
          yarn install --frozen-lockfile

      - name: 🧪 Esperar banco de dados
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Esperando o banco subir..."
            sleep 2
          done

      - name: 🧹 Rodar Lint
        run: yarn lint

      - name: 🧪 Rodar Testes
        env:
          DATABASE_URL: postgresql://postgres:12345678@localhost:5432/url_shortener_api_db
          JWT_SECRET: my_jwt_secret
          AUTH_SERVICE_PORT: 3000
          BASE_AUTH_SERVICE_URL: http://localhost:3000
          AUTH_SERVICE_SWAGGER_PATH: api/docs

          URL_SHORTENER_SERVICE_PORT: 3001
          BASE_URL_SHORTENER_SERVICE_URL: http://localhost:3001
          URL_SHORTENER_SERVICE_SWAGGER_PATH: api/docs
        run: yarn test
